### ISSUE TITLE
Atom package

### ISSUE THREAD

**Issue by danielbuechele** [arijs/prettier-with-tabs#2]
I created an Atom package forking `prettier-atom` to make your package available in Atom: https://atom.io/packages/prettier-atom-with-tabs

We could update the readme in this repo to use this Atom package. What do you think?

**Comment by rhengles** [comment]
Yes, that would be awesome! 🎉 Can you make a PR?

**Comment by rhengles** [comment]
@danielbuechele Alright, I got it fixed now! thanks! 👍
